### ISSUE TITLE
Cactu integration with LLM models

### ISSUE THREAD

**Issue by sergiuszlts** [Evolveye/Cactu-discord.js#3]
In an era of increasing opportunities related to the development of artificial intelligence, I am addressing the proposal to implement AI in this project. 

**I open the discussion.**

**Comment by Evolveye** [comment]
Hi @sergiuszlts!
I think the discussion is going to be really short ;p

This project, named "cactu-discord.js", is slowly transforming into something like "cactu-bot-framework.js". This is because currently, you can replace a single (albeit somewhat long) file, which is the only one containing Discord.js usage.

I want to extract this file from the core of the project. You will then be able to simply create a chatbot with any functionalities for any platform. This project is essentially a text token processor.

So, you can even create a microservice from it. You can write commands or filters that fetch external APIs (for example, Latex, WolframAlpha, or OpenAI) and return them as responses in your chat. This is why I will not implement AI directly inside this project; it serves as a module or interface for other functionalities.
